mohammadalnajar/social-media-app

- client/postcss.config.js
- client/tailwind.config.js
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> eslint fix client

- .github/workflows/client.yaml
- .github/workflows/server.yaml
- README.md
- server/package.json
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> Config workflow server

- server/middlewares/auth.js
- using email instead of username on the logging in process.
> login with email instead of username

- server/config/session.js
- server/controllers/users.js
- server/index.js
- We implemented the express session on the server.
- sessions will be stored in mongoDB
- session cookie will be sent with each request,
> mongo session implemented + send back as cookie

- client/src/utils/api.js
- server/controllers/users.js
- server/index.js
- server/middlewares/isLoggedIn.js
- server/routes/users.js
- middleware added to check if the user logged in or not.
- route made to send user data if the user is logged in.
- allow sending and receiving cookies between client and server.
> Get user data

- server/.eslintrc.json
- server/config/session.js
- server/controllers/users.js
- server/middlewares/auth.js
- server/middlewares/isJson.js
- server/models/User.js
- server/routes/users.js
- server/utils/mongoErrors.js
- deleted old mongoose validations
- more fields added to the user schema
- check if we received an empty object with log in route
- check for JSON content-type middleware added
> Fix #user model

- client/src/utils/api.js
- server/controllers/users.js
- server/routes/users.js
- log out feature added
- login route modified
- logout controller made 
- user will be logged out through destroying session
> Logout user

- client/src/features/entry/components/FormWrapper.jsx
- client/src/features/entry/components/RegisterForm.jsx
- improved register error handling
- fixed jumpiness when toggling between register and login
> Register fixes

- client/src/App.js
- client/src/components/layout/MainLayout.jsx
> style layout

- client/public/index.html
- client/src/components/LoadingPage.jsx
- client/src/context/authContext.js
- client/src/routes/index.jsx
- client/src/routes/protected.js
- client/src/utils/api.js
- server/config/session.js
- AuthContext cleanup
- check for user data onRefresh
- add extra check for protected route
- redirect to login if user not authenticated
- redirect to feed if user authenticated
fix the routes #36 
router bug #34
> Routes fix

- client/src/routes/index.jsx
- client/src/routes/protected.js
- removed unused code from index.js
- added extra conditions inside the protected routes
- added loading page when user data is still fetching
> protected routes refactor

- .vscode/settings.json
- client/package-lock.json
- client/package.json
- client/src/components/NotFound.jsx
- client/src/components/layout/MainLayout.jsx
- client/src/features/createPost/components/CreatePostHeader.jsx
- client/src/features/createPost/components/CreatePostModal.jsx
- client/src/features/createPost/components/CreatePostSelect.jsx
- client/src/features/createPost/components/ImageDropzone.jsx
- client/src/features/createPost/components/ImagePreview.jsx
- client/src/routes/index.jsx
- client/src/utils/api.js
- client/src/utils/constants.js
- client/tailwind.config.js
- Added drag and drop component.
- Added functionality to create new posts.
- Moved constants to separate file.
> Create new post

- .vscode/settings.json
- client/src/features/createPost/components/CreatePostModal.jsx
- client/src/features/createPost/components/ImageDropzone.jsx
- client/src/utils/api.js
- client/src/utils/constants.js
- server/config/cloudinary.js
- server/controllers/posts.js
- server/controllers/uploadImages.js
- server/index.js
- server/package-lock.json
- server/package.json
- server/routes/upload.js
Server:
- new route and controller added to save images on cloud
- set json limit to 50mb
Client:
- new func to save img on cloud
- converted img to str
> Uplaod img on cloud

- server/.eslintrc.json
- server/api/getRandomAvatar.js
- server/api/uploadImageToCloud.js
- server/controllers/uploadImages.js
- server/controllers/users.js
- server/models/User.js
- server/package-lock.json
- server/package.json
- get random avatar when user register
- convert image to base64
- upload avatar to Cloudinary
- save URL in user schema
- function to upload images made
Fixes #52
> Get random avatar

- server/utils/validationPatterns.js
- allow white spaces in first name and lastName
Fixes #25
> register bug fixed (white spaces)

- server/models/Post.js
- server/models/User.js
- date issue fixed in post and user models.
> date bug fixed

- client/src/features/createPost/components/CreatePostModal.jsx
- server/api/uploadImageToCloud.js
- server/controllers/posts.js
- server/controllers/uploadImages.js
- server/middlewares/checkPostAuthor.js
- server/models/Post.js
- server/routes/posts.js
- server/utils/getPublicId.js
- save public id in db when create post.
- delete image from loud before delete post from db
- added middleware to check the post author.
Fixes #69
> Delete img cloud

- README.md
- client/src/components/post/PostList.jsx
- client/src/components/post/components/PostAuthor.jsx
- server/README.md
- server/controllers/posts.js
- server/models/Post.js
- modifying post schema in db
- save userId when create the post in db
- put userData in each post obj
- implement the feature in the frondend
Fixes #70 
> User details post

- server/controllers/posts.js
- server/routes/posts.js
- check post author before editing or deleting a post
Fixes #65
> check post author before edit post

- client/src/components/post/PostList.jsx
- client/src/components/post/components/PostAuthor.jsx
- client/src/components/post/components/PostAuthorAction.jsx
- client/src/components/post/components/PostComment.jsx
- client/src/utils/timeElapsed.js
> post timing bug

- client/src/components/post/PostList.jsx
- server/controllers/posts.js
- server/utils/helpers.js
- sort posts in the server instead of in the client
Fixes #71
> Sort posts

- client/src/components/NavBar/components/optionsMenu/dropdown/Dropdown.jsx
- log user out when session is expired also
Fixes #61
> log user out when session is expired

- server/config/session.js
- server/index.js
- client deployed on heroku: https://social-media-app-97.herokuapp.com/
- client is also deployed on Netlify: https://vigorous-stonebraker-b37dd8.netlify.app/
- server is deployed on Heroku: https://social-media-97-api.herokuapp.com/
> Deployment

- client/src/hooks/useDarkMode.js
- give default value when app first time renders
Fixes #88 
> fix dark mode toggle BUG

- server/controllers/posts.js
- check if post has image before delete
- delete post also if it has no images
Fixes #92
> check if post has image before delete

- client/src/components/post/PostList.jsx
- client/src/components/post/components/PostMedia.jsx
- client/src/features/createPost/CreatePost.jsx
- added condition to prevent unauthorized post edits
> postAction authorization

- client/src/components/postModal/PostModal.jsx
- client/src/components/postModal/api.js
- one req to create post refactored in client code
> Refactor post create client

- client/src/components/postModal/PostModal.jsx
- client/src/components/postModal/hooks/useDropZone.js
- client/src/components/postModal/hooks/usePost.js
- Added fix to reset post modal content after editing
- Refactored post modal into 2 separate hooks
> edit post content fix

- client/src/components/navbar/Nav.jsx
- client/src/components/navbar/components/features/search/components/SearchField.jsx
- client/src/components/navbar/components/optionsMenu/OptionsMenu.jsx
- client/src/components/navbar/components/tabsMenu/TabsMenu.jsx
- client/src/components/post/components/PostAuthorAction.jsx
- client/src/features/entry/EntryLayout.jsx
- client/src/features/entry/components/FormButton.jsx
- client/src/features/entry/components/LoginForm.jsx
- client/src/features/entry/components/RegisterForm.jsx
- client/tailwind.config.js
- added loading icon in login btn
- added loading icon in register btn
- added loading icon in delete post btn
- navigate to feed after register
- center tabsMenu on big screen + full width optionmenu on small
- fix login form width 
Fixes #91
> Loading spinners

- client/src/components/navbar/components/features/messenger/components/MessengerIcon.jsx
- client/src/components/navbar/components/features/notifications/components/NotificationsIcon.jsx
- client/src/components/navbar/components/tabsMenu/Tab.jsx
- show tooltips only on large screens
- fix issue with tooltips of messenger and notifications
Fixes #115
> Tooltips fix

- client/src/components/ErrorAlert.jsx
- client/src/components/post/PostList.jsx
- client/src/components/post/components/PostAuthorAction.jsx
- client/src/components/post/components/postActions/PostStats.jsx
- client/src/components/post/components/postActions/comments/Comment.jsx
- client/src/components/post/hooks/useAction.js
- client/src/components/post/hooks/useComment.js
- client/src/components/postModal/hooks/usePost.js
- client/src/hooks/useLogout.js
- server/config/session.js
- redirect the user to login if the session is expired
- capitalize user names
Fixes #126 #124 
> Small fixes

- client/src/components/ErrorAlert.jsx
- client/src/components/post/PostList.jsx
- client/src/components/post/components/PostAuthorAction.jsx
- client/src/components/post/components/postActions/PostStats.jsx
- client/src/components/post/components/postActions/comments/Comment.jsx
- client/src/components/post/hooks/useAction.js
- client/src/components/post/hooks/useComment.js
- client/src/components/postModal/hooks/usePost.js
- client/src/hooks/useLogout.js
- show data users for comments , likes and dislikes
Fixes #122
> Show users data hover

- client/src/features/entry/components/FormWrapper.jsx
- client/src/features/entry/components/RegisterForm.jsx
- client/src/features/entry/hooks/useValidations.js
- show validation errors on all fields
- reset error messages onChange onput
- reset all errors on submit
Fixes #138 
> Register error handling

- client/src/components/post/api.js
- client/src/components/post/hooks/useAction.js
- client/src/components/post/hooks/useComment.js
- client/src/components/post/hooks/usePostActions.js
- client/src/utils/constants.js
- server/controllers/posts.js
- server/routes/posts.js
- route made to get pot stats
- controller built  to get post stats
- change the logic of post hooks
- get rid of multi[ple queries and replace with just one query per post
Fixes #121 
> Refactor post logic front
